version: '3.1'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'Bookshop'
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_USER: 'db_bookshop'
      MYSQL_PASSWORD: '54321'
      
    ports:
      - 3306:3306
  adminer:
    image: adminer:4.7.8
    restart: always
    ports:
      - 8081:8080