"""empty message

Revision ID: 08faa824c6ae
Revises: 
Create Date: 2022-05-16 23:07:43.539451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08faa824c6ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('author', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('is_in_stock', sa.Boolean(), nullable=True),
    sa.Column('genre', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=30), nullable=True),
    sa.Column('publisher', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Books')
    # ### end Alembic commands ###
